"use client";

import * as React from "react";
import { Info, BadgeCheck, FlaskConical, Globe2, AlertTriangle } from "lucide-react";
import { cn } from "@/lib/utils";
import type { DataQuality } from "@/types/search";

export const DATA_QUALITY_LABELS: Record<DataQuality, string> = {
  demo: "Demo Data",
  estimated: "Estimated",
  public_metadata: "Public Metadata",
  verified: "Verified",
};

export const DATA_QUALITY_DESCRIPTIONS: Record<DataQuality, string> = {
  demo: "Synthetic numbers generated by SN Adobe Analytic for demonstration. Not real Adobe Stock metrics.",
  estimated: "Computed from observable signals (e.g. a formula over public metadata). Approximate, not authoritative.",
  public_metadata: "Pulled directly from publicly visible Adobe Stock pages. Reflects what Adobe shows publicly.",
  verified: "Sourced from an authoritative first-party feed — official Adobe API or a contributor's own export.",
};

const STYLES: Record<DataQuality, { chip: string; banner: string; Icon: React.ElementType }> = {
  demo: {
    chip: "bg-amber-100 text-amber-800 border-amber-200",
    banner: "bg-amber-50 border-amber-200 text-amber-900",
    Icon: FlaskConical,
  },
  estimated: {
    chip: "bg-sky-100 text-sky-800 border-sky-200",
    banner: "bg-sky-50 border-sky-200 text-sky-900",
    Icon: Info,
  },
  public_metadata: {
    chip: "bg-violet-100 text-violet-800 border-violet-200",
    banner: "bg-violet-50 border-violet-200 text-violet-900",
    Icon: Globe2,
  },
  verified: {
    chip: "bg-emerald-100 text-emerald-800 border-emerald-200",
    banner: "bg-emerald-50 border-emerald-200 text-emerald-900",
    Icon: BadgeCheck,
  },
};

export type DataQualitySize = "xs" | "sm" | "md";

const SIZE_CLASSES: Record<DataQualitySize, string> = {
  xs: "px-1.5 py-0 text-[10px] gap-1 rounded-full leading-tight",
  sm: "px-2 py-0.5 text-[11px] gap-1 rounded-full leading-tight",
  md: "px-2.5 py-1 text-xs gap-1.5 rounded-full leading-tight",
};

interface DataQualityBadgeProps {
  level: DataQuality;
  size?: DataQualitySize;
  showLabel?: boolean;
  className?: string;
  /** Optional override for the tooltip explanation. */
  description?: string;
}

export function DataQualityBadge({
  level,
  size = "sm",
  showLabel = true,
  className,
  description,
}: DataQualityBadgeProps) {
  const { chip, Icon } = STYLES[level];
  const label = DATA_QUALITY_LABELS[level];
  const tooltip = description ?? DATA_QUALITY_DESCRIPTIONS[level];
  return (
    <span
      title={tooltip}
      aria-label={`${label}. ${tooltip}`}
      className={cn(
        "inline-flex items-center border font-semibold uppercase tracking-wide whitespace-nowrap",
        chip,
        SIZE_CLASSES[size],
        className,
      )}
    >
      <Icon className={size === "xs" ? "h-2.5 w-2.5" : "h-3 w-3"} aria-hidden />
      {showLabel ? <span>{label}</span> : null}
    </span>
  );
}

interface DataQualityBannerProps {
  level: DataQuality;
  providerName?: string;
  message?: string;
  className?: string;
  compact?: boolean;
}

export function DataQualityBanner({
  level,
  providerName,
  message,
  className,
  compact = false,
}: DataQualityBannerProps) {
  const { banner, Icon } = STYLES[level];
  const label = DATA_QUALITY_LABELS[level];
  const description = message ?? DATA_QUALITY_DESCRIPTIONS[level];
  return (
    <div
      role="status"
      className={cn(
        "flex items-start gap-3 rounded-xl border px-4 py-3 text-sm",
        banner,
        compact && "py-2 text-xs",
        className,
      )}
    >
      <Icon className="mt-0.5 h-4 w-4 flex-none" aria-hidden />
      <div className="min-w-0">
        <div className="flex flex-wrap items-center gap-x-2 gap-y-1 font-semibold uppercase tracking-wide">
          <span>{label}</span>
          {providerName ? (
            <span className="text-[11px] font-normal normal-case opacity-80">
              · {providerName}
            </span>
          ) : null}
        </div>
        <div
          className={cn(
            "mt-0.5 text-current/80 font-normal",
            compact ? "text-[11px]" : "text-xs",
          )}
        >
          {description}
        </div>
      </div>
    </div>
  );
}

interface UnverifiedFigureProps {
  level: DataQuality;
  children: React.ReactNode;
  className?: string;
}

/**
 * Wraps a number / metric with a small badge so the user always sees which
 * data-quality tier it belongs to.
 */
export function UnverifiedFigure({
  level,
  children,
  className,
}: UnverifiedFigureProps) {
  return (
    <span className={cn("inline-flex flex-wrap items-center gap-1.5", className)}>
      {children}
      <DataQualityBadge level={level} size="xs" />
    </span>
  );
}

export { AlertTriangle };
